(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="TA_ULTIMATE_V2";
const defaults={lang:"ru",theme:"dark",balance:10000,progress:[],journal:[],positions:[],plan:"",checks:{},quiz:{score:0,total:0,answered:0}};
let state;try{state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"));state.progress=Array.isArray(state.progress)?state.progress:[];state.journal=Array.isArray(state.journal)?state.journal:[];state.positions=Array.isArray(state.positions)?state.positions:[];state.checks=state.checks||{};state.quiz=state.quiz||defaults.quiz}catch(e){state={...defaults}};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const toast=m=>{const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2200)};
const safe=(name,fn)=>{try{fn()}catch(e){console.error(name,e);const er=$("#error");if(er){er.style.display="block";er.textContent="Module error: "+name+"\n"+e.message}}};
window.addEventListener("error",e=>{const er=$("#error");if(er){er.style.display="block";er.textContent="JavaScript error: "+e.message}});
const courses=[
["01","Основы рынка","Рынок, валютные пары, Bid/Ask, spread, ликвидность",6],
["02","Свечи","Свечи, структура, импульс и волатильность",6],
["03","Технический анализ","Тренды, уровни, зоны и структура рынка",7],
["04","Price Action","Сценарий входа, подтверждение и invalidation",6],
["05","Управление риском","Риск, размер позиции, R:R и drawdown",6],
["06","Психология","Дисциплина, FOMO и revenge trading",5],
["07","Strategy Lab","Создание, backtest и улучшение системы",8],
["08","Trading Plan","Правила, сессии, чек-листы и журнал",5],
["09","Advanced","Liquidity, BOS, CHOCH и confluence",5],
["10","Final Lab","Практические кейсы и итоговая проверка",6],
["11","Analytics","Win rate, expectancy, R-multiple и статистика",4],
["12","Trader OS","Собственная рабочая система трейдера",4]
];
const lessons=[
["Рынок и его участники","Цена двигается потому, что в рынке встречаются покупатели и продавцы. Трейдеру важно сначала понимать контекст, а не искать случайную кнопку BUY или SELL.","Пример: если цена последовательно формирует более высокие максимумы и минимумы, структура указывает на восходящее движение.",["Что в первую очередь показывает структура рынка?","Только размер свечи","Последовательность максимумов и минимумов","Цвет интерфейса","Баланс счёта"],1],
["Bid, Ask и Spread","Bid — цена, по которой рынок покупает у тебя. Ask — цена, по которой ты покупаешь. Разница между ними называется spread.","Пример: Bid 1.1000 и Ask 1.1002 дают spread 0.0002.",["Что такое spread?","Комиссия за интернет","Разница между Bid и Ask","Размер депозита","Количество свечей"],1],
["Ликвидность","Ликвидность показывает, насколько легко исполнять сделки без сильного влияния на цену. Высокая ликвидность обычно означает более активный рынок и более плотное исполнение.","Перед входом оценивай время сессии, новости и инструмент.",["Что означает высокая ликвидность?","Рынок невозможно закрыть","Сделки обычно легче исполняются","Цена всегда растёт","Риск равен нулю"],1],
["Японская свеча","Свеча показывает Open, High, Low и Close. Тело показывает расстояние между открытием и закрытием, тени — экстремумы периода.","Не делай вывод по одной свече без контекста.",["Что показывает тело свечи?","Только максимум","Расстояние между Open и Close","Только минимум","Размер депозита"],1],
["Импульс и волатильность","Импульс — направленное ускорение движения. Волатильность описывает величину колебаний цены. Они помогают оценить контекст и риск.","Сильный импульс не является гарантией продолжения.",["Что описывает волатильность?","Величину колебаний цены","Пароль аккаунта","Только спред","Количество уроков"],0],
["Поддержка и сопротивление","Уровни — зоны, где цена раньше реагировала. В реальной торговле это не магические линии, а области вероятного поведения участников.","Используй зоны вместе с контекстом и подтверждением.",["Что правильнее считать поддержкой?","Всегда одну идеальную цену","Зону, где цена исторически реагировала","Любую зелёную свечу","Только дневной максимум"],1],
["Тренд","Восходящий тренд характеризуется серией higher highs и higher lows. Нисходящий — lower highs и lower lows.","Трендовый контекст помогает не торговать против структуры без причины.",["Что характерно для восходящего тренда?","HH и HL","Только красные свечи","Всегда боковик","Отсутствие движения"],0],
["Market Structure","BOS означает пробой структуры в направлении движения. CHOCH часто используют как сигнал возможного изменения характера движения.","Это элементы анализа, а не гарантии результата.",["Что обычно означает BOS?","Пробой значимой структуры","Закрытие брокера","Размер спреда","Смена языка"],0],
["Risk Management","Главная задача риска — ограничить ущерб одной сделки. Размер позиции должен зависеть от допустимого риска и расстояния до стопа.","Пример: при депозите $10 000 и риске 1% максимальный денежный риск — $100.",["Сколько составляет 1% от $10 000?","$10","$50","$100","$1 000"],2],
["R:R","Risk-to-Reward сравнивает потенциальный риск и целевую прибыль. Например, 1:2 означает цель в два раза больше принятого риска.","R:R сам по себе не делает стратегию прибыльной.",["Что означает R:R 1:2?","Риск вдвое больше цели","Цель примерно вдвое больше риска","Две сделки вместо одной","Два индикатора"],1],
["Drawdown","Drawdown — снижение капитала от предыдущего максимума до последующего минимума. Контроль просадки помогает сохранять рабочий капитал.","Большая просадка усложняет восстановление счёта.",["Что такое drawdown?","Снижение капитала от пика","Комиссия брокера","Количество сделок","Размер свечи"],0],
["FOMO","FOMO — страх упустить движение. Он часто заставляет входить поздно и без подтверждения.","Правило: если setup пропущен, следующий качественный setup важнее желания догнать цену.",["Что описывает FOMO?","Страх упустить движение","Расчёт спреда","Сильную ликвидность","Тестовую валюту"],0],
["Revenge trading","Revenge trading — попытка эмоционально отыграться после убытка. Это может разрушить заранее установленный риск.","После убытка сначала оцени план и состояние, а не увеличивай размер позиции.",["Что является примером revenge trading?","Увеличить риск из злости после убытка","Закрыть терминал по плану","Записать сделку в журнал","Проверить новости"],0],
["Trading Plan","Торговый план фиксирует рынки, сетапы, риск, время торговли и запреты. Он превращает решения в повторяемый процесс.","Хороший план должен быть понятен до открытия сделки.",["Когда лучше знать риск сделки?","После убытка","До входа","После месяца","Никогда"],1],
["Journal","Журнал сохраняет контекст сделки: setup, вход, риск, результат, эмоции и ошибки. Он нужен для анализа повторяющихся закономерностей.","Запись без контекста мало полезна.",["Зачем нужен торговый журнал?","Чтобы анализировать процесс и ошибки","Чтобы гарантировать прибыль","Чтобы увеличить кредитное плечо","Чтобы заменить план"],0]
];
const tr={ru:{
loading:"Запуск академии...",home:"Главная",academyNav:"Академия",terminalNav:"Терминал",analyticsNav:"Аналитика",toolsNav:"Инструменты",live:"СИМУЛЯЦИЯ РЫНКА ONLINE",hero1:"Торгуй умнее.",hero2:"Учись как профессионал.",herop:"Интерактивная среда для изучения рынка, анализа графиков и безопасной практики без реальных денег.",openTerminal:"Открыть терминал ↗",startLearning:"Начать обучение",modules:"модулей",lessons:"уроков",demo:"demo",demoFeed:"DEMO FEED",why:"Не просто сайт. Твоя торговая среда.",fTitle1:"Реалистичный терминал",fTitle2:"Система обучения",fTitle3:"Аналитика трейдера",fTitle4:"Создано для телефона",f1:"График со свечами, таймфреймы, сделки и открытые позиции.",f2:"Уроки, вопросы, тесты, прогресс и достижения.",f3:"Журнал сделок, риск, статистика и личный торговый план.",f4:"Интерфейс адаптирован под телефон — всё главное в несколько касаний.",academy:"Академия трейдера",academyp:"От нуля до системного подхода. Открывай уроки, отвечай на вопросы и закрепляй знания.",progress:"прогресс",academyStatus:"Твой прогресс",continue:"Продолжить обучение",quizHub:"Центр тестов",terminalTitle:"Демо-торговый терминал",terminalDesc:"Рыночная симуляция. Все сделки виртуальные и не используют реальные деньги.",demoBalance:"ДЕМО БАЛАНС",quickOrder:"Быстрый ордер",instrument:"Инструмент",positionSize:"Размер позиции",risk:"Риск",sell:"SELL",buy:"BUY",openPositions:"Открытые позиции",analyticsTitle:"Аналитика трейдера",analyticsDesc:"Смотри на свои решения как на систему.",winrate:"Win rate",fromJournal:"по журналу",trades:"Сделки",records:"записей",avgResult:"средний результат",learning:"Обучение",academySmall:"академия",performance:"Карта результатов",checklist:"Чек-лист трейдера",checkPlan:"Есть план",checkRisk:"Риск рассчитан",checkSetup:"Есть setup",checkEmotion:"Эмоции под контролем",toolsTitle:"Профессиональные инструменты",toolsDesc:"Инструменты, которые помогают подготовиться до сделки.",riskCalc:"Калькулятор риска",balanceLabel:"Баланс",riskPct:"Риск %",entry:"Вход",stop:"Стоп",calculate:"Рассчитать риск",journalTitle:"Торговый журнал",saveTrade:"Сохранить сделку",planTitle:"Торговый план",savePlan:"Сохранить план",disclaimer:"Только образовательная демо-среда · Не финансовая рекомендация · Реальные деньги не используются",nextQuestion:"Следующий вопрос",quizKicker:"QUIZ LAB",quizTitle:"Центр тестов",quizDesc:"Проверь знания по всем модулям."},
tj:{
loading:"Академия оғоз шуда истодааст...",home:"Асосӣ",academyNav:"Академия",terminalNav:"Терминал",analyticsNav:"Таҳлил",toolsNav:"Асбобҳо",live:"СИМУЛЯТСИЯИ БОЗОР ФАЪОЛ АСТ",hero1:"Оқилонатар савдо кун.",hero2:"Мисли профессионал омӯз.",herop:"Муҳити интерактивӣ барои омӯзиши бозор, таҳлили график ва таҷрибаи бехатар бе пули воқеӣ.",openTerminal:"Терминалро кушо ↗",startLearning:"Омӯзишро оғоз кун",modules:"модул",lessons:"дарс",demo:"demo",demoFeed:"DEMO FEED",why:"Ин танҳо сайт нест. Муҳити савдои ту.",fTitle1:"Терминали воқеӣ",fTitle2:"Системаи омӯзиш",fTitle3:"Таҳлили трейдер",fTitle4:"Барои телефон сохта шудааст",f1:"Графики шамъӣ, таймфреймҳо, аҳдҳо ва позицияҳои кушода.",f2:"Дарсҳо, саволҳо, тестҳо, прогресс ва дастовардҳо.",f3:"Журнали аҳдҳо, риск, статистика ва нақшаи шахсии савдо.",f4:"Интерфейс барои телефон сохта шудааст — ҳама чиз бо чанд ламс.",academy:"Академияи трейдер",academyp:"Аз сифр то системаи равшан. Дарсро кушо, ба савол ҷавоб деҳ ва донишро мустаҳкам кун.",progress:"пешравӣ",academyStatus:"Пешравии ту",continue:"Омӯзишро идома деҳ",quizHub:"Маркази тестҳо",terminalTitle:"Терминали демо-савдо",terminalDesc:"Ин симулятсияи бозор аст. Ҳамаи аҳдҳо виртуалӣ мебошанд.",demoBalance:"БАЛАНСИ ДЕМО",quickOrder:"Ордeри зуд",instrument:"Асбоб",positionSize:"Андозаи позиция",risk:"Риск",sell:"ФУРӮШ",buy:"ХАРИД",openPositions:"Позицияҳои кушода",analyticsTitle:"Таҳлили трейдер",analyticsDesc:"Қарорҳои худро ҳамчун як система бин.",winrate:"Фоизи бурд",fromJournal:"аз журнал",trades:"Аҳдҳо",records:"сабт",avgResult:"натиҷаи миёна",learning:"Омӯзиш",academySmall:"академия",performance:"Харитаи натиҷаҳо",checklist:"Чек-листи трейдер",checkPlan:"Нақша ҳаст",checkRisk:"Риск ҳисоб шудааст",checkSetup:"Setup ҳаст",checkEmotion:"Эҳсосот зери назорат",toolsTitle:"Асбобҳои касбӣ",toolsDesc:"Асбобҳое, ки пеш аз аҳд ба омодагӣ кӯмак мекунанд.",riskCalc:"Ҳисобкунаки риск",balanceLabel:"Баланс",riskPct:"Риск %",entry:"Вуруд",stop:"Стоп",calculate:"Рискро ҳисоб кун",journalTitle:"Журнали савдо",saveTrade:"Аҳдро нигоҳ дор",planTitle:"Нақшаи савдо",savePlan:"Нақшаро нигоҳ дор",disclaimer:"Танҳо муҳити таълимии демо · Маслиҳати молиявӣ нест · Пули воқеӣ истифода намешавад",nextQuestion:"Саволи навбатӣ",quizKicker:"QUIZ LAB",quizTitle:"Маркази тестҳо",quizDesc:"Дониши худро аз рӯи ҳамаи модулҳо санҷ."}};
function language(){const d=tr[state.lang]||tr.ru;$$("[data-i]").forEach(e=>{const k=e.dataset.i;if(d[k])e.textContent=d[k]});$("#lang").textContent=state.lang==="ru"?"TJ":"RU";document.documentElement.lang=state.lang;$("#lessonExample")?.setAttribute("dir",state.lang==="tj"?"ltr":"ltr");renderCourses();updateAcademyStatus();renderQuizHome()}
function nav(){const go=id=>{$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===id));$("#mobileNav")?.classList.remove("open");if(id==="learn")renderCourses();scrollTo({top:0,behavior:"smooth"})};$$("[data-view]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.view)));$("#menu")?.addEventListener("click",()=>$("#mobileNav").classList.toggle("open"))}
function theme(){document.body.classList.toggle("light",state.theme==="light");$("#theme").textContent=state.theme==="light"?"☀":"☾";$("#theme").onclick=()=>{state.theme=state.theme==="light"?"dark":"light";save();theme()};$("#lang").onclick=()=>{state.lang=state.lang==="ru"?"tj":"ru";save();language()}}
function candles(canvas,seed=1){if(!canvas)return;const c=canvas.getContext("2d"),d=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;canvas.width=w*d;canvas.height=h*d;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);let price=50,data=[];for(let i=0;i<65;i++){const o=price;price+=(Math.sin(i*.43+seed)*2)+(Math.random()-.45)*3;const cl=price,hi=Math.max(o,cl)+Math.random()*5+1,lo=Math.min(o,cl)-Math.random()*5-1;data.push({o,cl,hi,lo})}const min=Math.min(...data.map(a=>a.lo)),max=Math.max(...data.map(a=>a.hi)),sy=v=>h-22-(v-min)/(max-min)*(h-44);c.strokeStyle="rgba(130,160,145,.11)";for(let j=1;j<5;j++){const y=h*j/5;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}const gap=w/data.length;data.forEach((a,i)=>{const x=i*gap+gap/2,y1=sy(a.hi),y2=sy(a.lo),yo=sy(a.o),yc=sy(a.cl);c.strokeStyle=a.cl>=a.o?"#43e58c":"#ff6675";c.fillStyle=c.strokeStyle;c.beginPath();c.moveTo(x,y1);c.lineTo(x,y2);c.stroke();c.fillRect(x-gap*.27,Math.min(yo,yc),gap*.54,Math.max(2,Math.abs(yc-yo)))})}
function lessonData(index){const base=lessons[index%lessons.length];return {title:base[0],text:base[1],example:base[2],q:base[3],correct:base[4]}}
function completed(i){return state.progress.includes(i)}
function renderCourses(){const box=$("#courses");if(!box)return;const total=courses.reduce((a,x)=>a+x[3],0),done=state.progress.length;$("#learnPct").textContent=Math.min(100,Math.round(done/total*100))+"%";box.innerHTML=courses.map((c,i)=>{const d=Array.from({length:c[3]},(_,n)=>i+"-"+n).filter(completed).length,p=Math.round(d/c[3]*100);const first=Array.from({length:c[3]},(_,n)=>i+"-"+n).findIndex(x=>!completed(x));return '<article class="course panel"><span class="course-num">'+c[0]+' · MODULE</span><h3>'+c[1]+'</h3><p>'+c[2]+'</p><div class="bar"><i style="display:block;width:'+p+'%;height:4px;background:#43e58c;border-radius:5px"></i></div><small class="muted">'+d+'/'+c[3]+' '+(state.lang==="tj"?"дарс":"уроков")+'</small><br><button data-openlesson="'+i+'" data-lesson="'+Math.max(0,first)+'">'+(d>=c[3]?(state.lang==="tj"?"Такрор кун":"Повторить"):(state.lang==="tj"?"Дарсро кушо":"Открыть урок"))+'</button></article>'}).join("");$$("[data-openlesson]").forEach(b=>b.onclick=()=>openLesson(+b.dataset.openlesson));updateAcademyStatus()}
function updateAcademyStatus(){const total=courses.reduce((a,x)=>a+x[3],0),done=state.progress.length,e=$("#academyStatusText");if(e)e.textContent=state.lang==="tj"?done+" аз "+total+" дарс анҷом ёфт":done+" из "+total+" уроков завершено"}
let lessonSession={module:0,lesson:0,correct:false};
function openLesson(module){const c=courses[module],d=Array.from({length:c[3]},(_,n)=>module+"-"+n).findIndex(x=>!completed(x));const lessonIndex=d<0?0:d;lessonSession={module,lesson:lessonIndex,correct:false};showLesson()}
function showLesson(){const m=lessonSession.module,n=lessonSession.lesson,global=(m*2+n)%lessons.length,d=lessonData(global);$("#lessonKicker").textContent=courses[m][0]+" · "+courses[m][1]+" · "+(n+1)+"/"+courses[m][3];$("#lessonTitle").textContent=d.title;$("#lessonText").textContent=d.text;$("#lessonExample").innerHTML="<b>"+(state.lang==="tj"?"Мисол":"Пример")+"</b><br>"+d.example;$("#questionNumber").textContent=(state.lang==="tj"?"Савол":"Вопрос")+" · 1";$("#questionText").textContent=state.lang==="tj"?translateQuestion(d.q):d.q;const answers=$("#answers");answers.innerHTML=d.q.slice(1).map((a,i)=>'<button class="answer" data-answer="'+i+'">'+translateAnswer(a)+'</button>').join("");$("#answerFeedback").textContent="";$("#nextQuestion").disabled=true;$("#nextQuestion").textContent=tr[state.lang].nextQuestion;$("#lessonModal").classList.add("open");$$(".answer").forEach(b=>b.onclick=()=>checkLesson(+b.dataset.answer,d.correct,d));}
function translateQuestion(q){const map={"Что в первую очередь показывает структура рынка?":"Сохтори бозор пеш аз ҳама чиро нишон медиҳад?","Что такое spread?":"Spread чист?","Что означает высокая ликвидность?":"Ликвиднокии баланд чӣ маъно дорад?","Что показывает тело свечи?":"Бадани шамъ чиро нишон медиҳад?","Что описывает волатильность?":"Волатилнокӣ чиро нишон медиҳад?","Что правильнее считать поддержкой?":"Дурусттараш дастгирӣ чист?","Что характерно для восходящего тренда?":"Барои тренди болораванда чӣ хос аст?","Что обычно означает BOS?":"BOS одатан чӣ маъно дорад?","Сколько составляет 1% от $10 000?":"1% аз $10 000 чанд аст?","Что означает R:R 1:2?":"R:R 1:2 чӣ маъно дорад?","Что такое drawdown?":"Drawdown чист?","Что описывает FOMO?":"FOMO чиро тавсиф мекунад?","Что является примером revenge trading?":"Кадомаш мисоли revenge trading аст?","Когда лучше знать риск сделки?":"Риски аҳдро кай бояд донист?","Зачем нужен торговый журнал?":"Журнали савдо барои чӣ лозим аст?"};return state.lang==="tj"?(map[q]||q):q}
function translateAnswer(a){if(state.lang==="ru")return a;const map={"Только размер свечи":"Танҳо андозаи шамъ","Последовательность максимумов и минимумов":"Пайдарпаии максимумҳо ва минимумҳо","Цвет интерфейса":"Ранги интерфейс","Баланс счёта":"Баланси ҳисоб","Комиссия за интернет":"Комиссияи интернет","Разница между Bid и Ask":"Фарқи байни Bid ва Ask","Размер депозита":"Андозаи депозит","Количество свечей":"Шумораи шамъҳо","Рынок невозможно закрыть":"Бозорро бастан мумкин нест","Сделки обычно легче исполняются":"Аҳдҳо одатан осонтар иҷро мешаванд","Цена всегда растёт":"Нарх ҳамеша боло меравад","Риск равен нулю":"Риск сифр аст","Только максимум":"Танҳо максимум","Расстояние между Open и Close":"Масофаи байни Open ва Close","Только минимум":"Танҳо минимум","Величину колебаний цены":"Андозаи тағйирёбии нарх","Пароль аккаунта":"Рамзи аккаунт","Только спред":"Танҳо spread","Количество уроков":"Шумораи дарсҳо","Зону, где цена исторически реагировала":"Минтақае, ки нарх қаблан реаксия кардааст","Любую зелёную свечу":"Ҳар шамъи сабз","Только дневной максимум":"Танҳо максимуми рӯз","HH и HL":"HH ва HL","Только красные свечи":"Танҳо шамъҳои сурх","Всегда боковик":"Ҳамеша flat","Отсутствие движения":"Набудани ҳаракат","Пробой значимой структуры":"Шикасти сохтори муҳим","Закрытие брокера":"Бастани брокер","Размер спреда":"Андозаи spread","Смена языка":"Иваз кардани забон","$10":"$10","$50":"$50","$100":"$100","$1 000":"$1 000","Риск вдвое больше цели":"Риск ду баробар аз ҳадаф калон","Цель примерно вдвое больше риска":"Ҳадаф тақрибан ду баробар аз риск калон","Две сделки вместо одной":"Ду аҳд ба ҷойи як аҳд","Два индикатора":"Ду индикатор","Снижение капитала от пика":"Коҳиши капитал аз қулла","Комиссия брокера":"Комиссияи брокер","Размер свечи":"Андозаи шамъ","Страх упустить движение":"Тарси аз даст додани ҳаракат","Сильную ликвидность":"Ликвиднокии баланд","Тестовую валюту":"Асъори тестӣ","Увеличить риск из злости после убытка":"Пас аз зарар аз рӯи хашм рискро зиёд кардан","Закрыть терминал по плану":"Терминалро тибқи нақша бастан","Записать сделку в журнал":"Аҳдро дар журнал сабт кардан","Проверить новости":"Хабарҳоро санҷидан","После убытка":"Пас аз зарар","До входа":"Пеш аз вуруд","После месяца":"Пас аз як моҳ","Никогда":"Ҳеҷ гоҳ","Чтобы анализировать процесс и ошибки":"Барои таҳлили раванд ва хатогиҳо","Чтобы гарантировать прибыль":"Барои кафолати фоида","Чтобы увеличить кредитное плечо":"Барои зиёд кардани leverage","Чтобы заменить план":"Барои иваз кардани нақша"};return map[a]||a}
function checkLesson(answer,correct,d){$$(".answer").forEach(b=>b.disabled=true);const ok=answer===correct,fb=$("#answerFeedback");lessonSession.correct=ok;fb.className="answer-feedback "+(ok?"good":"bad");fb.textContent=ok?(state.lang==="tj"?"✓ Дуруст!":"✓ Верно!"):((state.lang==="tj"?"✗ Нодуруст. Ҷавоби дуруст: ":"✗ Неверно. Правильный ответ: ")+translateAnswer(d.q[correct+1]));$("#nextQuestion").disabled=false}
function nextLesson(){const m=lessonSession.module,n=lessonSession.lesson;if(lessonSession.correct){const id=m+"-"+n;if(!completed(id)){state.progress.push(id);save();renderCourses();analytics();toast(state.lang==="tj"?"Дарс анҷом ёфт ✓":"Урок завершён ✓")}const next=Array.from({length:courses[m][3]},(_,x)=>m+"-"+x).findIndex(x=>!completed(x));if(next>=0){lessonSession.lesson=next;showLesson()}else{$("#lessonModal").classList.remove("open");toast(state.lang==="tj"?"Модул пурра анҷом ёфт 🎉":"Модуль полностью завершён 🎉")}}else{showLesson()}}
function quizQuestions(){return lessons.map((x,i)=>({q:x[3][0],answers:x[3].slice(1),correct:x[4],i}))}
let quizState={index:0,score:0};
function renderQuizHome(){const box=$("#quizContent");if(!box)return;box.innerHTML='<div class="quiz-stats"><b>'+quizState.score+'</b><span>'+(state.lang==="tj"?"холи тест":"баллов")+'</span></div><button id="startQuiz" class="primary wide">'+(state.lang==="tj"?"Тестро оғоз кун":"Начать тест")+'</button>'}
function startQuiz(){quizState={index:0,score:0};renderQuizQuestion()}
function renderQuizQuestion(){const all=quizQuestions();if(quizState.index>=all.length){$("#quizContent").innerHTML='<div class="quiz-result"><div class="quiz-score">'+quizState.score+"/"+all.length+'</div><h3>'+(state.lang==="tj"?"Тест анҷом ёфт":"Тест завершён")+'</h3><p>'+(state.lang==="tj"?"Натиҷаро таҳлил кун ва дарсҳои нодурустро такрор намо.":"Проанализируй результат и повтори уроки с ошибками.")+'</p><button id="restartQuiz" class="primary wide">'+(state.lang==="tj"?"Аз нав":"Пройти снова")+'</button></div>';$("#restartQuiz").onclick=startQuiz;return}const d=all[quizState.index];$("#quizContent").innerHTML='<div class="quiz-progress">'+(quizState.index+1)+' / '+all.length+'</div><h3>'+translateQuestion(d.q)+'</h3><div class="answers">'+d.answers.map((a,i)=>'<button class="answer" data-qanswer="'+i+'">'+translateAnswer(a)+'</button>').join("")+'</div><div id="quizFeedback" class="answer-feedback"></div>';$$("[data-qanswer]").forEach(b=>b.onclick=()=>{const ok=+b.dataset.qanswer===d.correct;$$("[data-qanswer]").forEach(x=>x.disabled=true);if(ok)quizState.score++;$("#quizFeedback").className="answer-feedback "+(ok?"good":"bad");$("#quizFeedback").textContent=ok?(state.lang==="tj"?"✓ Дуруст":"✓ Верно"):(state.lang==="tj"?"✗ Нодуруст":"✗ Неверно");setTimeout(()=>{quizState.index++;renderQuizQuestion()},650)})}
function bindModals(){$$("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("open"));$$(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")}));$("#nextQuestion").onclick=nextLesson;$("#continueLearning").onclick=()=>{const idx=state.progress.length;let acc=0;for(let i=0;i<courses.length;i++){if(idx<acc+courses[i][3]){openLesson(i);return}acc+=courses[i][3]}toast(state.lang==="tj"?"Ҳамаи дарсҳо анҷом ёфтанд 🎉":"Все уроки уже завершены 🎉")};$("#quizHub").onclick=()=>{$("#quizModal").classList.add("open");renderQuizHome()};$("#quizContent").addEventListener("click",e=>{if(e.target.id==="startQuiz")startQuiz()})}
function market(){let p=2645.28;const tick=()=>{p+=((Math.random()-.46)*4);$("#heroPrice").textContent=p.toFixed(2);$("#heroChange").textContent=(Math.random()*.8-.15).toFixed(2)+"%";candles($("#heroChart"),Date.now()/100000)};tick();setInterval(tick,2200);candles($("#chart"),7)}
const prices={"EUR/USD":1.1742,"GBP/USD":1.3468,"USD/JPY":148.62,"XAU/USD":2645.28,"BTC/USD":66842};
function terminal(){const asset=$("#asset"),oa=$("#orderAsset");const update=()=>{const a=asset.value,v=prices[a];const n=v*(1+(Math.random()-.48)*.001);prices[a]=n;$("#terminalPrice").textContent=a==="BTC/USD"?n.toFixed(0):a==="XAU/USD"?n.toFixed(2):n.toFixed(4);$("#terminalPct").textContent=(Math.random()*.9-.3).toFixed(2)+"%";candles($("#chart"),Math.floor(n))};asset.onchange=()=>{oa.value=asset.value;update()};oa.onchange=()=>{asset.value=oa.value;update()};$$(".tf").forEach(b=>b.onclick=()=>{$$(".tf").forEach(x=>x.classList.remove("active"));b.classList.add("active");candles($("#chart"),b.dataset.tf.length*7)});$("#buy").onclick=()=>openPos("BUY");$("#sell").onclick=()=>openPos("SELL");setInterval(update,2600);update();renderPositions()}
function openPos(side){const a=$("#asset").value,q=Number($("#qty").value)||.1,entry=prices[a];state.positions.push({id:Date.now(),side,a,q,entry});state.balance-=Math.min(10,q*2);save();renderPositions();toast(side+" · "+a+" · DEMO")}
function renderPositions(){const box=$("#positions");if(!box)return;$("#posCount").textContent=state.positions.length;box.innerHTML=state.positions.map(p=>'<div class="position"><b style="color:'+(p.side==="BUY"?"#43e58c":"#ff6675")+'">'+p.side+'</b> · '+p.a+' · '+p.q+'<br><span class="muted">Entry '+p.entry+'</span></div>').join("")||'<span class="muted">No open positions</span>';$("#balance").textContent="$"+state.balance.toLocaleString(undefined,{minimumFractionDigits:2})}
function tools(){const calc=()=>{const b=+$("#rb").value||0,p=+$("#rp").value||0,e=+$("#re").value||0,s=+$("#rs").value||0;const risk=b*p/100,dist=e?Math.abs(e-s)/e*100:0;$("#riskResult").textContent=(state.lang==="tj"?"Миқдори риск: $":"Risk amount: $")+risk.toFixed(2)+" · "+(state.lang==="tj"?"Масофа: ":"Distance: ")+dist.toFixed(2)+"%"};$("#calcRisk").onclick=calc;calc();$("#journalForm").onsubmit=e=>{e.preventDefault();state.journal.unshift({a:$("#jasset").value||"—",r:+$("#jr").value||0,res:$("#jresult").value,n:$("#jnote").value});save();e.target.reset();journal();analytics();toast(state.lang==="tj"?"Аҳд нигоҳ дошта шуд ✓":"Сделка сохранена ✓")};$("#savePlan").onclick=()=>{state.plan=$("#plan").value;save();$("#planSaved").textContent=state.lang==="tj"?"Нигоҳ дошта шуд ✓":"Сохранено локально ✓";toast(state.lang==="tj"?"Нақша нигоҳ дошта шуд":"Торговый план сохранён")};$("#plan").value=state.plan;journal()}
function journal(){const box=$("#journalList");if(!box)return;box.innerHTML=state.journal.slice(0,6).map(x=>'<div class="journal-item"><b>'+x.a+'</b> · '+x.res+' · '+x.r+'R<br><span class="muted">'+(x.n||"No note")+'</span></div>').join("")}
function analytics(){const n=state.journal.length,w=state.journal.filter(x=>x.res==="win").length,r=state.journal.reduce((a,x)=>a+x.r,0);$("#winrate").textContent=n?Math.round(w/n*100)+"%":"0%";$("#trades").textContent=n;$("#avgr").textContent=(n?r/n:0).toFixed(2)+"R";const total=courses.reduce((a,x)=>a+x[3],0);$("#learnStat").textContent=Math.min(100,Math.round(state.progress.length/total*100))+"%";candles($("#performance"),17);$$("[data-check]").forEach(c=>{c.checked=!!state.checks[c.dataset.check];c.onchange=()=>{state.checks[c.dataset.check]=c.checked;save()}})}
function boot(){safe("navigation",nav);safe("theme",theme);safe("language",language);safe("academy",renderCourses);safe("market",market);safe("terminal",terminal);safe("tools",tools);safe("analytics",analytics);safe("modals",bindModals);$("#year").textContent=new Date().getFullYear();setTimeout(()=>$("#boot").classList.add("hide"),500)}
document.addEventListener("DOMContentLoaded",boot);
})();