(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY="TA_ULTIMATE_V6";
const MODULES=[
["01","Основы рынка",6],["02","Японские свечи",6],["03","Технический анализ",7],["04","Price Action",6],["05","Risk Management",6],["06","Психология",5],["07","Strategy Lab",8],["08","Trading Plan",5],["09","Advanced",5],["10","Final Lab",6],["11","Analytics",4],["12","Trader OS",4]];
const LESSONS=[
["Рынок и его участники","Рынок — система обмена активами. Трейдер изучает цену, ликвидность, время и контекст.","EUR/USD показывает относительную стоимость евро к доллару.","Что показывает рыночную структуру?",["Последовательность максимумов и минимумов","Цвет интерфейса","Размер депозита","Количество уроков"],0],
["Bid, Ask и Spread","Bid — цена продажи, Ask — цена покупки. Spread — разница между ними.","Bid 1.1741 и Ask 1.1743 дают spread 0.0002.","Что такое spread?",["Разница между Bid и Ask","Баланс счёта","Размер депозита","Количество свечей"],0],
["Ликвидность","Ликвидность описывает способность рынка проводить сделки без сильного изменения цены.","Активная сессия может давать более плотный рынок.","Что означает высокая ликвидность?",["Сделки обычно легче исполняются","Цена всегда растёт","Риск равен нулю","Рынок невозможно закрыть"],0],
["Японская свеча","Свеча показывает Open, High, Low и Close. Тело — расстояние между открытием и закрытием.","Большое тело после маленьких свечей может указывать на импульс.","Что показывает тело свечи?",["Расстояние между Open и Close","Только максимум","Только минимум","Пароль аккаунта"],0],
["Импульс и волатильность","Волатильность — величина колебаний цены. Импульс — заметное направленное движение.","Перед новостями диапазон может резко увеличиться.","Что описывает волатильность?",["Величину колебаний цены","Только spread","Смену языка","Количество уроков"],0],
["Поддержка и сопротивление","Уровень — зона, где цена исторически реагировала. Это не магическая линия.","Несколько реакций около одной зоны дают область интереса.","Что правильнее считать поддержкой?",["Зону, где цена исторически реагировала","Любую зелёную свечу","Только максимум","Только минимум"],0],
["Тренд","Восходящая структура обычно содержит повышающиеся максимумы и минимумы.","HH + HL — базовая модель восходящего тренда.","Что характерно для восходящего тренда?",["HH и HL","Только красные свечи","Всегда боковик","Отсутствие движения"],0],
["Market Structure","BOS часто означает пробой значимой структуры. CHoCH используют для описания возможной смены характера движения.","Закрытие выше swing high может быть структурным сигналом.","Что обычно означает BOS?",["Пробой значимой структуры","Закрытие брокера","Размер spread","Смена языка"],0],
["Risk Management","Риск задаётся до входа. При $10 000 и риске 1% плановый лимит потери — $100.","Размер позиции зависит от стопа и стоимости пункта.","Сколько составляет 1% от $10 000?",["$10","$50","$100","$1 000"],2],
["R:R","R:R сравнивает потенциальную прибыль и риск. 1:2 означает цель примерно вдвое больше риска.","Риск $100 и цель $200 дают 1:2.","Что означает R:R 1:2?",["Риск вдвое больше цели","Цель примерно вдвое больше риска","Две сделки вместо одной","Два индикатора"],1],
["Drawdown","Drawdown — снижение капитала от пика до последующего минимума.","Пик $10 500 и equity $9 975 дают снижение $525.","Что такое drawdown?",["Снижение капитала от пика","Комиссия брокера","Размер свечи","Страх упустить движение"],0],
["FOMO","FOMO — страх упустить движение. Он часто вызывает поздние входы без подтверждения.","Цена резко выросла, и трейдер входит только из страха пропустить движение.","Что описывает FOMO?",["Страх упустить движение","Сильную ликвидность","Тестовую валюту","Закрытие терминала"],0],
["Revenge trading","Revenge trading — попытка быстро отыграть убыток через увеличение риска или хаотичные сделки.","После стопа трейдер удваивает риск из злости.","Что является примером revenge trading?",["Увеличить риск из злости после убытка","Закрыть терминал по плану","Записать сделку","Проверить новости"],0],
["Trading Plan","План превращает идею в правила: рынок, сессия, setup, риск, вход, выход и запреты.","Перед неделей трейдер прописывает условия работы.","Когда лучше знать риск сделки?",["После убытка","До входа","После месяца","Никогда"],1],
["Journal","Журнал нужен для анализа процесса: причина входа, риск, результат, эмоции и ошибки.","После серии сделок можно сравнить setup и R.","Зачем нужен торговый журнал?",["Чтобы анализировать процесс и ошибки","Чтобы гарантировать прибыль","Чтобы увеличить плечо","Чтобы заменить план"],0]
];
const TJ=[
["Бозор ва иштирокчиёни он","Бозор — низоми мубодилаи активҳост. Трейдер нарх, ликвиднокӣ, вақт ва контекстро меомӯзад.","EUR/USD арзиши нисбии евро нисбат ба долларро нишон медиҳад."],
["Bid, Ask ва Spread","Bid — нархи фурӯш, Ask — нархи харид. Spread фарқи байни онҳо мебошад.","Bid 1.1741 ва Ask 1.1743 → spread 0.0002."],
["Ликвиднокӣ","Ликвиднокӣ қобилияти бозор барои иҷрои аҳдҳо бе тағйири зиёди нарх аст.","Дар сессияи фаъол иҷрои аҳдҳо метавонад осонтар бошад."],
["Шамъи японӣ","Шамъ Open, High, Low ва Close-ро нишон медиҳад. Тана масофаи байни кушодан ва бастан аст.","Танаи калон метавонад импулсро нишон диҳад."],
["Импулс ва волатилнокӣ","Волатилнокӣ андозаи тағйироти нарх аст. Импулс ҳаракати самтнок мебошад.","Пеш аз хабарҳо диапазон метавонад зиёд шавад."],
["Дастгирӣ ва муқовимат","Сатҳ минтақаест, ки нарх дар гузашта реаксия кардааст.","Якчанд реаксия метавонад минтақаи таваҷҷӯҳ бошад."],
["Тренд","Сохтори болораванда одатан максимумҳо ва минимумҳои баландтар дорад.","HH + HL модели одии тренди болораванда аст."],
["Сохтори бозор","BOS одатан шикасти сохтори муҳимро ифода мекунад.","Басташавии болотар аз swing high метавонад сигнали сохторӣ бошад."],
["Идоракунии риск","Риск пеш аз вуруд муайян мешавад. Барои $10 000 ва 1% лимит $100 аст.","Андозаи позиция аз стоп ва арзиши пункт вобаста аст."],
["R:R","R:R фоидаи эҳтимолиро бо риск муқоиса мекунад. 1:2 яъне ҳадаф тақрибан ду баробар аз риск калон аст.","$100 риск ва $200 ҳадаф = 1:2."],
["Drawdown","Drawdown коҳиши капитал аз қулла то минимуми баъдӣ мебошад.","$10 500 → $9 975 = $525 коҳиш."],
["FOMO","FOMO тарси аз даст додани ҳаракат аст.","Вуруди дер танҳо аз тарси аз даст додан мисоли FOMO мебошад."],
["Revenge trading","Revenge trading кӯшиши зуд баргардонидани зарар бо риск ё аҳдҳои бетартиб аст.","Пас аз стоп ду баробар кардани риск мисол аст."],
["Нақшаи савдо","Нақша идеяро ба қоидаҳо табдил медиҳад: бозор, setup, риск, вуруд ва баромад.","Рискро пеш аз ордер бояд донист."],
["Журнал","Журнал барои таҳлили раванд, натиҷа, эҳсосот ва хатогиҳо истифода мешавад.","Маълумоти журнал барои review ва такмил кӯмак мекунад."]
];
const T={ru:{home:"Главная",academy:"Академия",terminal:"Терминал",analytics:"Аналитика",tools:"Инструменты"},tj:{home:"Асосӣ",academy:"Академия",terminal:"Терминал",analytics:"Аналитика",tools:"Асбобҳо"}};
const DEFAULT={lang:"ru",theme:"dark",xp:0,progress:[],positions:[],history:[],journal:[],plan:"",checks:{},balance:10000};
let state;
try{state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){state=Object.assign({},DEFAULT)}
function cleanState(){state.lang=state.lang==="tj"?"tj":"ru";state.theme=state.theme==="light"?"light":"dark";state.xp=Number.isFinite(+state.xp)?+state.xp:0;state.balance=Number.isFinite(+state.balance)&&+state.balance>0?+state.balance:10000;["progress","positions","history","journal"].forEach(k=>{if(!Array.isArray(state[k]))state[k]=[]});if(!state.checks||typeof state.checks!=="object")state.checks={};if(typeof state.plan!=="string")state.plan=""}cleanState();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
const PRICES={"EUR/USD":1.1742,"GBP/USD":1.3468,"USD/JPY":148.62,"XAU/USD":2645.28,"BTC/USD":66842};
let prices=Object.assign({},PRICES),currentTF="1m",filter="all",lessonState={module:0,index:0,correct:false},quizState=null;
const fmt=(a,n)=>Number(a).toLocaleString("en-US",{minimumFractionDigits:n,maximumFractionDigits:n});
const decimals=a=>a==="BTC/USD"?0:(a==="XAU/USD"||a==="USD/JPY"?2:4);
function toast(s){const x=$("#toast");x.textContent=s;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),1800)}
function rnd(n){const x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)}
function candles(seed,count=80,base=50){let p=base,a=[];for(let i=0;i<count;i++){let o=p;p+=(rnd(seed+i*.73)-.48)*3+Math.sin(i*.31+seed)*.9;let c=p,h=Math.max(o,c)+1+rnd(seed+i)*4,l=Math.min(o,c)-1-rnd(seed+i*2)*4;a.push({o,c,h,l,v:300+Math.floor(rnd(seed+i*4)*900)})}return a}
function drawChart(canvas,data){if(!canvas)return;const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(240,r.width),h=Math.max(160,r.height);canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext("2d");x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.strokeStyle="rgba(130,160,145,.12)";for(let i=1;i<6;i++){x.beginPath();x.moveTo(0,h*i/6);x.lineTo(w,h*i/6);x.stroke()}let lo=Math.min(...data.map(z=>z.l)),hi=Math.max(...data.map(z=>z.h));if(hi===lo)hi=lo+1;const sy=v=>h-18-(v-lo)/(hi-lo)*(h-36),gap=w/data.length;data.forEach((z,i)=>{const xx=i*gap+gap/2,up=z.c>=z.o;x.strokeStyle=up?"#46ed91":"#ff6675";x.fillStyle=x.strokeStyle;x.beginPath();x.moveTo(xx,sy(z.h));x.lineTo(xx,sy(z.l));x.stroke();x.fillRect(xx-gap*.3,Math.min(sy(z.o),sy(z.c)),Math.max(2,gap*.6),Math.max(2,Math.abs(sy(z.c)-sy(z.o))))});return data.at(-1)}
function view(name){$$(".view").forEach(v=>v.classList.toggle("active",v.id===name));$$(".desktop-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$("#mobileNav").classList.remove("open");if(name==="terminal")renderTerminal();if(name==="analytics")renderAnalytics();if(name==="learn")renderAcademy();window.scrollTo({top:0,behavior:"smooth"})}
function applyTheme(){document.body.classList.toggle("light",state.theme==="light");$("#themeBtn").textContent=state.theme==="light"?"☀":"☾"}
function applyLanguage(){document.documentElement.lang=state.lang;$("#langBtn").textContent=state.lang==="ru"?"TJ":"RU";$$("[data-key]").forEach(b=>{const k=b.dataset.key;if(T[state.lang][k])b.textContent=T[state.lang][k]})}
function renderHome(){const rows=[["EUR/USD",prices["EUR/USD"],.31],["GBP/USD",prices["GBP/USD"],.18],["USD/JPY",prices["USD/JPY"],-.22],["XAU/USD",prices["XAU/USD"],.42],["BTC/USD",prices["BTC/USD"],1.08]];$("#ticker").innerHTML=rows.map(r=>'<div><b>'+r[0]+'</b> '+fmt(r[1],decimals(r[0]))+' <i class="'+(r[2]>=0?"good":"bad")+'">'+(r[2]>=0?"+":"")+r[2].toFixed(2)+"%</i></div>").join("");$("#homeXP").textContent=state.xp;const w=state.journal.filter(x=>x.res==="win").length;$("#homeWin").textContent=(state.journal.length?Math.round(w/state.journal.length*100):0)+"%";$("#homeEquity").textContent="$"+state.balance.toFixed(2);drawChart($("#heroChart"),candles(2,72,50));}
function renderAcademy(){const done=state.progress.length;$("#progressPct").textContent=Math.round(done/68*100)+"%";$("#progressText").textContent=done+" из 68 уроков завершено";$("#progressBar").style.width=Math.min(100,done/68*100)+"%";$("#xp").textContent=state.xp;$("#level").textContent=state.xp>=900?"Master":state.xp>=400?"Advanced":state.xp>=100?"Trader":"Novice";const list=MODULES.map((m,i)=>{const n=state.progress.filter(x=>x.startsWith(i+"-")).length,isDone=n>=m[2],isOpen=n>0||i===0;return {m,i,n,isDone,isOpen}}).filter(o=>filter==="done"?o.isDone:filter==="open"?o.isOpen:true);$("#courses").innerHTML=list.map(o=>'<article class="course glass '+(o.isDone?"done":"")+'"><span class="course-num">'+o.m[0]+' · MODULE</span><h3>'+o.m[1]+'</h3><p>'+o.n+'/'+o.m[2]+' уроков · '+(o.isDone?"Module completed":"Практика + checkpoint")+'</p><div class="course-bar"><i style="width:'+Math.round(o.n/o.m[2]*100)+'%"></i></div><small>'+Math.round(o.n/o.m[2]*100)+'%</small><button data-action="course" data-module="'+o.i+'">'+(o.isDone?"Review module":"Open module")+'</button></article>').join("")||'<div class="glass course"><h3>No modules</h3></div>'}
function openCourse(m){let n=0;while(n<MODULES[m][2]&&state.progress.includes(m+"-"+n))n++;lessonState={module:m,index:Math.min(n,MODULES[m][2]-1),correct:false};renderLesson()}
function lessonData(){return LESSONS[(lessonState.module*5+lessonState.index)%LESSONS.length]}
function renderLesson(){const d=lessonData(),t=state.lang==="tj"?TJ[(lessonState.module*5+lessonState.index)%TJ.length]:[d[0],d[1],d[2]];$("#lessonKicker").textContent=MODULES[lessonState.module][0]+" · "+MODULES[lessonState.module][1];$("#lessonProgress").textContent=(lessonState.index+1)+"/"+MODULES[lessonState.module][2];$("#lessonTitle").textContent=t[0];$("#lessonText").textContent=t[1];$("#lessonPoints").innerHTML='<div class="point">✓ '+(state.lang==="tj"?"Фаҳмиши мафҳум":"Ключевой принцип")+'</div><div class="point">✓ '+(state.lang==="tj"?"Мисоли амалӣ":"Практический контекст")+'</div>';$("#lessonExample").innerHTML="<b>"+(state.lang==="tj"?"Мисол":"Пример")+"</b><br>"+t[2];$("#questionText").textContent=d[3];$("#answers").innerHTML=d[4].map((a,i)=>'<button data-action="answer" data-answer="'+i+'">'+a+'</button>').join("");$("#feedback").textContent="";$("#nextLesson").disabled=true;$("#lessonModal").classList.add("open")}
function answer(i){const d=lessonData();lessonState.correct=i===d[5];$$("[data-action=answer]").forEach((b,n)=>{b.disabled=true;b.classList.toggle("correct",n===d[5]);b.classList.toggle("wrong",n===i&&i!==d[5])});$("#feedback").textContent=lessonState.correct?"✓ Верно! +10 XP":"✗ Неверно. Правильный ответ: "+d[4][d[5]];$("#feedback").className=lessonState.correct?"good":"bad";$("#nextLesson").disabled=false}
function nextLesson(){if(!lessonState.correct)return;const id=lessonState.module+"-"+lessonState.index;if(!state.progress.includes(id)){state.progress.push(id);state.xp+=10;save()}if(lessonState.index+1<MODULES[lessonState.module][2]){lessonState.index++;lessonState.correct=false;renderLesson();renderAcademy()}else{$("#lessonModal").classList.remove("open");renderAcademy();toast("Модуль завершён 🎉")}}
function startQuiz(){const pool=[...LESSONS].sort(()=>Math.random()-.5).slice(0,12);quizState={pool,i:0,score:0};$("#quizModal").classList.add("open");renderQuiz()}
function renderQuiz(){if(quizState.i>=quizState.pool.length){$("#quizContent").innerHTML='<div class="quiz-score">'+quizState.score+'/'+quizState.pool.length+'</div><h2>Quiz завершён</h2><p>Результат сохранён в текущей сессии.</p><button class="btn primary wide" data-action="quizAgain">Пройти снова</button>';return}const d=quizState.pool[quizState.i];$("#quizContent").innerHTML='<div class="quiz-progress">'+(quizState.i+1)+' / '+quizState.pool.length+'</div><h3>'+d[3]+'</h3><div class="answers">'+d[4].map((a,i)=>'<button data-action="quizAnswer" data-answer="'+i+'">'+a+'</button>').join("")+'</div>'}
function quizAnswer(i){const d=quizState.pool[quizState.i];$$("[data-action=quizAnswer]").forEach((b,n)=>{b.disabled=true;b.classList.toggle("correct",n===d[5]);b.classList.toggle("wrong",n===i&&n!==d[5])});if(i===d[5])quizState.score++;setTimeout(()=>{quizState.i++;renderQuiz()},350)}
function syncPrices(){Object.keys(prices).forEach(a=>{const f=a==="BTC/USD"?0.0015:.0007;prices[a]*=1+(Math.random()-.5)*f});renderTerminal();renderHome()}
function renderTerminal(){const a=$("#assetSelect").value,v=prices[a];$("#orderSelect").value=a;$("#terminalPrice").textContent=fmt(v,decimals(a));$("#terminalMove").textContent=(Math.random()>.5?"+":"-")+(Math.random()*.5).toFixed(2)+"%";$("#entry").textContent=fmt(v,decimals(a));$("#risk").textContent="$"+(state.balance*(+$("#riskPct").value||1)/100).toFixed(2);const d=candles(v+currentTF.length,90,v/10);const last=drawChart($("#tradeChart"),d);$("#co").textContent=fmt(last.o,decimals(a));$("#ch").textContent=fmt(last.h,decimals(a));$("#cl").textContent=fmt(last.l,decimals(a));$("#cc").textContent=fmt(last.c,decimals(a));$("#cv").textContent=last.v;const floating=state.positions.reduce((s,p)=>s+pnl(p),0);$("#balance").textContent="$"+state.balance.toFixed(2);$("#equity").textContent="$"+(state.balance+floating).toFixed(2);$("#free").textContent="$"+(state.balance+floating-state.positions.length*50).toFixed(2);$("#posCount").textContent=state.positions.length;$("#positions").innerHTML=state.positions.map(p=>'<div class="position"><button class="close" data-action="closePosition" data-id="'+p.id+'">×</button><b class="'+(p.side==="BUY"?"good":"bad")+'">'+p.side+'</b> '+p.asset+' · '+p.qty+'<br><span>Entry '+fmt(p.entry,decimals(p.asset))+' · P&L <b class="'+(pnl(p)>=0?"good":"bad")+'">'+pnl(p).toFixed(2)+'</b></span></div>').join("")||'<span style="color:var(--muted);font-size:11px">No open positions.</span>';$("#history").innerHTML=state.history.slice(0,20).map(x=>'<div class="history-row"><b>'+x.asset+'</b><span>'+x.side+'</span><span>'+x.qty+'</span><span>'+x.time+'</span><b class="'+(x.pnl>=0?"good":"bad")+'">'+x.pnl.toFixed(2)+'</b></div>').join("")||'<span style="color:var(--muted);font-size:11px">No closed trades.</span>'}
function pnl(p){return(prices[p.asset]-p.entry)*(p.side==="BUY"?1:-1)*p.qty*(p.asset==="XAU/USD"?10:p.asset==="BTC/USD"?1:1000)}
function openPosition(side){const a=$("#assetSelect").value,q=Math.max(.01,+$("#qty").value||.1);state.positions.push({id:Date.now()+Math.random(),asset:a,side,qty:q,entry:prices[a],time:new Date().toLocaleTimeString()});save();renderTerminal();toast(side+" · "+a+" · DEMO")}
function closePosition(id){const p=state.positions.find(x=>String(x.id)===String(id));if(!p)return;const r=pnl(p);state.balance+=r;state.history.unshift({asset:p.asset,side:p.side,qty:p.qty,pnl:r,time:new Date().toLocaleString()});state.positions=state.positions.filter(x=>String(x.id)!==String(id));save();renderTerminal();renderAnalytics();toast("Position closed: "+r.toFixed(2))}
function calcRisk(){const b=+$("#rb").value||0,r=+$("#rp").value||0,e=+$("#re").value||0,s=+$("#rs").value||0,t=+$("#rt").value||0,risk=b*r/100,dist=Math.abs(e-s),rr=dist?Math.abs(t-e)/dist:0;$("#rrcalc").value=rr.toFixed(2);$("#riskResult").innerHTML="Risk: <b>$"+risk.toFixed(2)+"</b> · Stop distance: "+dist.toFixed(4)+" · R:R <b>1:"+rr.toFixed(2)+"</b>"}
function renderAnalytics(){const j=state.journal,w=j.filter(x=>x.res==="win").length,sum=j.reduce((a,x)=>a+(+x.r||0),0);let eq=0,peak=0,dd=0,best=0,cur=0,vals=[0];j.forEach(x=>{eq+=+x.r||0;vals.push(eq);peak=Math.max(peak,eq);dd=Math.min(dd,eq-peak);if(+x.r>0){cur++;best=Math.max(best,cur)}else cur=0});$("#winRate").textContent=(j.length?Math.round(w/j.length*100):0)+"%";$("#expectancy").textContent=(j.length?sum/j.length:0).toFixed(2)+"R";$("#drawdown").textContent=dd.toFixed(2)+"R";$("#streak").textContent=best;$("#tradeCount").textContent=j.length+" trades";$("#breakdown").innerHTML=[["Wins",w],["Losses",j.filter(x=>x.res==="loss").length],["Break-even",j.filter(x=>x.res==="be").length],["Total R",sum.toFixed(2)+"R"],["Learning",Math.round(state.progress.length/68*100)+"%"]].map(x=>'<div class="breakdown-row"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join("");drawLine($("#equityChart"),vals);$$("[data-check]").forEach(x=>{x.checked=!!state.checks[x.dataset.check]})}
function drawLine(c,vals){if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(250,r.width),h=Math.max(180,r.height);c.width=w*d;c.height=h*d;const x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.strokeStyle="rgba(130,160,145,.12)";for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,h*i/5);x.lineTo(w,h*i/5);x.stroke()}let mi=Math.min(-1,...vals),ma=Math.max(1,...vals);x.strokeStyle="#46ed91";x.lineWidth=2;x.beginPath();vals.forEach((v,i)=>{const xx=12+i*(w-24)/Math.max(1,vals.length-1),yy=h-18-(v-mi)/(ma-mi)*(h-36);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()}
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="trade-academy-backup.json";a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm("Сбросить весь локальный прогресс, журнал и demo-счёт?")){localStorage.removeItem(KEY);location.reload()}}
function saveJournal(){const f=$("#journalForm");if(!f)return;state.journal.unshift({asset:$("#jasset").value||"—",res:$("#jresult").value,r:+$("#jr").value||0,emotion:$("#jemotion").value,setup:$("#jsetup").value||"—",note:$("#jnote").value||"—",time:new Date().toLocaleString()});save();renderJournal();renderAnalytics();f.reset();toast("Trade saved ✓")}
function renderJournal(){$("#journalList").innerHTML=state.journal.slice(0,10).map(x=>'<div class="journal-item"><b>'+x.asset+'</b> · '+x.res+' · '+x.r+'R<br><span>'+x.setup+' · '+x.emotion+' · '+x.note+'</span></div>').join("")||'<span style="color:var(--muted);font-size:11px">No journal entries.</span>'}
function bind(){document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const a=b.dataset.action;if(a==="view")view(b.dataset.view);else if(a==="menu")$("#mobileNav").classList.toggle("open");else if(a==="lang"){state.lang=state.lang==="ru"?"tj":"ru";save();applyLanguage();renderAcademy();toast(state.lang==="tj"?"Забон: тоҷикӣ":"Язык: русский")}else if(a==="theme"){state.theme=state.theme==="dark"?"light":"dark";save();applyTheme()}else if(a==="continue"){let found=false;for(let i=0;i<MODULES.length;i++){for(let n=0;n<MODULES[i][2];n++)if(!state.progress.includes(i+"-"+n)){openCourse(i);found=true;break}if(found)break}if(!found)toast("Все уроки завершены 🎉")}else if(a==="course")openCourse(+b.dataset.module);else if(a==="answer")answer(+b.dataset.answer);else if(a==="nextLesson")nextLesson();else if(a==="quiz")startQuiz();else if(a==="quizAgain")startQuiz();else if(a==="quizAnswer")quizAnswer(+b.dataset.answer);else if(a==="closeModal")b.closest(".modal").classList.remove("open");else if(a==="indicators")$("#indicatorPanel").classList.toggle("open");else if(a==="tf"){currentTF=b.dataset.tf;$$("[data-action=tf]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTerminal()}else if(a==="buy"||a==="sell")openPosition(a==="buy"?"BUY":"SELL");else if(a==="closePosition")closePosition(b.dataset.id);else if(a==="clearHistory"){state.history=[];save();renderTerminal();toast("History cleared")}else if(a==="calcRisk")calcRisk();else if(a==="savePlan"){state.plan=$("#plan").value;save();$("#planSaved").textContent="Saved locally ✓";toast("Plan saved")}else if(a==="export")exportData();else if(a==="reset")resetData();else if(a==="filter"){filter=b.dataset.filter;$$("[data-action=filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderAcademy()}});
document.addEventListener("change",e=>{const c=e.target;if(c.matches("[data-check]")){state.checks[c.dataset.check]=c.checked;save()}if(c.dataset.change==="asset"){renderTerminal()}if(c.dataset.change==="orderAsset"){$("#assetSelect").value=c.value;renderTerminal()}});
document.addEventListener("input",e=>{if(e.target.id==="riskPct"){const v=state.balance*(+e.target.value||1)/100;$("#risk").textContent="$"+v.toFixed(2)}});
$("#journalForm").addEventListener("submit",e=>{e.preventDefault();saveJournal()});
$("#mobileNav").addEventListener("click",e=>{if(e.target.closest("button"))$("#mobileNav").classList.remove("open")})}
function boot(){applyTheme();applyLanguage();renderHome();renderAcademy();renderTerminal();renderAnalytics();renderJournal();$("#plan").value=state.plan;bind();setInterval(syncPrices,3000);window.addEventListener("resize",()=>{renderHome();if($("#terminal").classList.contains("active"))renderTerminal();if($("#analytics").classList.contains("active"))renderAnalytics()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();